import { Challenge } from "./types";
import { defaultSchool } from "./schools";

export const STANDARD_RUBRIC = [
  {
    criterion: "Technical Execution",
    maxScore: 5,
    description: "How well the project was built and how reliably it works.",
  },
  {
    criterion: "Creativity & Innovation",
    maxScore: 5,
    description: "Originality of the approach and the idea behind it.",
  },
  {
    criterion: "Presentation & Communication",
    maxScore: 5,
    description: "How clearly the team explained the problem and the solution.",
  },
  {
    criterion: "Collaboration & Process",
    maxScore: 5,
    description: "Evidence of teamwork and how the project came together.",
  },
];

export const challenges: Challenge[] = [
  {
    id: "challenge-ai-sprint",
    title: "AI & Automation Sprint",
    theme: "AI & Automation",
    sponsor: null,
    coverIcon: "Sparkles",
    colorFrom: "#6366f1",
    colorTo: "#a855f7",
    shortDescription:
      "Build a small AI or automation tool that solves a real problem at school.",
    brief:
      "Teams design and build a lightweight AI-powered or automated tool that addresses a real problem students or staff deal with every day — think scheduling, tutoring, communication, or workflow busywork. Projects are judged on execution, creativity, and how clearly the team can explain the impact.",
    status: "closed",
    format: "team",
    difficulty: "intermediate",
    minTeamSize: 2,
    maxTeamSize: 4,
    skillTags: ["Python", "Machine Learning", "Automation"],
    toolTags: ["Python", "OpenAI API", "Zapier"],
    rubric: STANDARD_RUBRIC,
    reward: "$500 tech grant + AI Explorer badge",
    registrationOpens: "2026-07-20",
    startDate: "2026-08-01",
    submissionDeadline: "2026-08-21",
    resultsDate: "2026-08-28",
    schoolId: defaultSchool.id,
  },
  {
    id: "challenge-cyber-ctf",
    title: "Cybersecurity Capture-the-Flag",
    theme: "Cybersecurity",
    sponsor: "Aegis Cyber Range",
    coverIcon: "Shield",
    colorFrom: "#0ea5e9",
    colorTo: "#0f172a",
    shortDescription:
      "Solve a series of security puzzles as a team and defend your findings.",
    brief:
      "Sponsored by Aegis Cyber Range, this challenge is a real-world security case study: teams get hands-on access to Aegis's hosted cyber range — the same SOC and pentest tooling their analysts use — to work through a simulated network intrusion. Teams work through a series of flags covering network security, basic forensics, and web vulnerabilities, then submit a short writeup of how they solved each one. No prior CTF experience required — just curiosity and a willingness to Google things at 11pm.",
    status: "open",
    format: "team",
    difficulty: "advanced",
    minTeamSize: 2,
    maxTeamSize: 3,
    skillTags: ["Cybersecurity", "Networking", "Linux"],
    toolTags: ["Kali Linux", "Wireshark", "Splunk", "CTFd"],
    rubric: STANDARD_RUBRIC,
    reward: "Aegis Cyber Range certification + invite to the regional CTF competition",
    registrationOpens: "2026-08-25",
    startDate: "2026-09-05",
    submissionDeadline: "2026-09-26",
    resultsDate: "2026-10-03",
    schoolId: defaultSchool.id,
  },
  {
    id: "challenge-community-data",
    title: "Community Impact Data Challenge",
    theme: "Data Analytics",
    sponsor: null,
    coverIcon: "BarChart3",
    colorFrom: "#16a34a",
    colorTo: "#0d9488",
    shortDescription:
      "Turn public community data into a story that could change a local policy.",
    brief:
      "Teams pick a local dataset (school attendance, park usage, recycling rates — your call) and build a short data story: what's happening, why it matters, and one recommendation. Great entry point for students who want to work with real numbers without writing a lot of code.",
    status: "in_progress",
    format: "team",
    difficulty: "beginner",
    minTeamSize: 2,
    maxTeamSize: 4,
    skillTags: ["Data Analysis", "Community Impact", "Presentation"],
    toolTags: ["Tableau", "Google Sheets", "Canva"],
    rubric: STANDARD_RUBRIC,
    reward: "Feature in the district newsletter + $250 grant",
    registrationOpens: "2026-08-10",
    startDate: "2026-08-24",
    submissionDeadline: "2026-09-14",
    resultsDate: "2026-09-21",
    schoolId: defaultSchool.id,
  },
  {
    id: "challenge-fin-lit-jam",
    title: "Financial Literacy Design Jam",
    theme: "Business & Entrepreneurship",
    sponsor: null,
    coverIcon: "PiggyBank",
    colorFrom: "#f59e0b",
    colorTo: "#ea580c",
    shortDescription:
      "Design a tool or mini-lesson that makes personal finance click for teens.",
    brief:
      "Teams design a bite-sized product — an app concept, a game, a short interactive lesson — that teaches a personal finance skill (budgeting, credit, saving) in a way that actually holds a teenager's attention. Registration opens soon.",
    status: "upcoming",
    format: "team",
    difficulty: "beginner",
    minTeamSize: 1,
    maxTeamSize: 3,
    skillTags: ["Business", "Financial Literacy", "Presentation"],
    toolTags: ["Figma", "Excel"],
    rubric: STANDARD_RUBRIC,
    reward: "Sponsor mentorship session",
    registrationOpens: "2026-09-22",
    startDate: "2026-10-01",
    submissionDeadline: "2026-10-19",
    resultsDate: "2026-10-26",
    schoolId: defaultSchool.id,
  },
  {
    id: "challenge-robotics-expo",
    title: "Robotics & Automation Expo",
    theme: "Engineering",
    sponsor: "ELS-Tec Group",
    coverIcon: "Cog",
    colorFrom: "#64748b",
    colorTo: "#1e293b",
    shortDescription:
      "Design and demo a small automated build for a live expo showcase.",
    brief:
      "Sponsored by ELS-Tec Group, this challenge invites teams to design a small robotics or automation build — from a sorting arm to a simple sensor-driven gadget — and demo it live at the fall expo. Documentation and a short demo video are required alongside the build.",
    status: "closed",
    format: "team",
    difficulty: "intermediate",
    minTeamSize: 2,
    maxTeamSize: 4,
    skillTags: ["Robotics", "Engineering", "Python"],
    toolTags: ["Arduino", "Python", "CAD"],
    rubric: STANDARD_RUBRIC,
    reward: "Robotics kit for your team + expo showcase spot",
    registrationOpens: "2026-07-28",
    startDate: "2026-08-08",
    submissionDeadline: "2026-08-29",
    resultsDate: "2026-09-05",
    schoolId: defaultSchool.id,
  },
];

export function getChallengeById(id: string): Challenge | undefined {
  return challenges.find((c) => c.id === id);
}
