import { Student } from "./types";
import { defaultSchool } from "./schools";

export const students: Student[] = [
  {
    id: "student-zoe",
    name: "Zoe Whitfield",
    avatarSeed: "Zoe Whitfield",
    grade: "11th Grade",
    bio: "Interested in machine learning and how automation can solve real school problems.",
    skillTags: ["Python", "Machine Learning", "Public Speaking"],
    xp: 2380,
    badgeIds: ["first-submission", "team-player", "ai-explorer", "top-scorer"],
    schoolId: defaultSchool.id,
  },
  {
    id: "student-owen",
    name: "Owen Park",
    avatarSeed: "Owen Park",
    grade: "11th Grade",
    bio: "Data nerd who likes turning messy spreadsheets into something useful.",
    skillTags: ["Python", "Data Analysis"],
    xp: 1960,
    badgeIds: ["first-submission", "team-player", "ai-explorer"],
    schoolId: defaultSchool.id,
  },
  {
    id: "student-sofia",
    name: "Sofia Ramirez",
    avatarSeed: "Sofia Ramirez",
    grade: "12th Grade",
    bio: "Designer first, coder second. Believes good UX wins projects.",
    skillTags: ["UI/UX Design", "Prompt Engineering"],
    xp: 2100,
    badgeIds: ["first-submission", "team-player", "ai-explorer", "rising-star"],
    schoolId: defaultSchool.id,
  },
  {
    id: "student-devon",
    name: "Devon Brooks",
    avatarSeed: "Devon Brooks",
    grade: "10th Grade",
    bio: "Building toward a cybersecurity career, one CTF at a time.",
    skillTags: ["JavaScript", "Networking"],
    xp: 1340,
    badgeIds: ["first-submission", "team-player"],
    schoolId: defaultSchool.id,
  },
  {
    id: "student-priya",
    name: "Priya Patel",
    avatarSeed: "Priya Patel",
    grade: "10th Grade",
    bio: "Loves dashboards, cloud infrastructure, and clean data pipelines.",
    skillTags: ["Cloud Computing", "Data Analysis"],
    xp: 1500,
    badgeIds: ["first-submission", "team-player"],
    schoolId: defaultSchool.id,
  },
  {
    id: "student-jalen",
    name: "Jalen Wright",
    avatarSeed: "Jalen Wright",
    grade: "9th Grade",
    bio: "New to Catalyst OS but already tinkering with robotics kits at home.",
    skillTags: ["Python", "Robotics"],
    xp: 1260,
    badgeIds: ["first-submission", "team-player", "rising-star"],
    schoolId: defaultSchool.id,
  },
  {
    id: "student-ines",
    name: "Ines Okafor",
    avatarSeed: "Ines Okafor",
    grade: "12th Grade",
    bio: "Runs the school's cybersecurity club and never met a firewall she didn't want to test.",
    skillTags: ["Cybersecurity", "Linux"],
    xp: 1780,
    badgeIds: ["first-submission", "team-player", "security-sleuth"],
    schoolId: defaultSchool.id,
  },
  {
    id: "student-marcus",
    name: "Marcus Lee",
    avatarSeed: "Marcus Lee",
    grade: "11th Grade",
    bio: "Networking enthusiast, still deciding between IT and cybersecurity as a path.",
    skillTags: ["Networking", "Cybersecurity"],
    xp: 990,
    badgeIds: ["first-submission"],
    schoolId: defaultSchool.id,
  },
  {
    id: "student-amara",
    name: "Amara Johnson",
    avatarSeed: "Amara Johnson",
    grade: "9th Grade",
    bio: "Just joined Catalyst OS this semester — the Robotics Expo was her first challenge.",
    skillTags: ["Graphic Design", "Video Production"],
    xp: 820,
    badgeIds: ["first-submission", "team-player"],
    schoolId: defaultSchool.id,
  },
];

export const currentStudentId = "student-zoe";

export function getStudentById(id: string): Student | undefined {
  return students.find((s) => s.id === id);
}
